cloud:
  aws:
    s3:
      bucket: umchwan
    credentials:
      access-key: AKIAWXPJQASFWFX7YU6G
      secret-key: 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
      instanceProfile: true
    region:
      static: ap-northeast-2
    stack:
      auto: false


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB