server:
  port: 8080

spring:
  application:
    name: informeAPISB

  datasource:
    url: jdbc:mysql://umchwan-db.crl3pba9zxfa.ap-northeast-2.rds.amazonaws.com:3306/umchwanDB
    username: admin
    password: 20000530
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false